name: uefi_simulator
description: "this app provides a simplified environment to simulate UEFI (Unified Extensible Firmware Interface) for training purposes. "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.2.3
  yaml: ^3.1.2
  csv: ^6.0.0
  package_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/